//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class GUI_bezahlung extends JPanel {
    private JButton zehnc;
    private JButton zwanzigc;
    private JButton eins;
    private JButton fuenfc;
    private JButton fuenfzig;
    private JPasswordField jcomp6;
    private JPasswordField jcomp7;
    private JLabel jcomp8;
    private JLabel jcomp9;
    private JButton fuenf;
    private JButton zehn;
    private JButton zwei;
    private JButton zwanzig;

    public GUI_bezahlung() {
        //construct components
        zehnc = new JButton ("0,10");
        zwanzigc = new JButton ("0,20");
        eins = new JButton ("1,00");
        fuenfc = new JButton ("0,05");
        fuenfzig = new JButton ("0,50");
        jcomp6 = new JPasswordField (5);
        jcomp7 = new JPasswordField (5);
        jcomp8 = new JLabel ("bereits gezahlt:");
        jcomp9 = new JLabel ("noch zu Zahlen:");
        fuenf = new JButton ("5,00");
        zehn = new JButton ("10,00");
        zwei = new JButton ("2,00");
        zwanzig = new JButton ("20,00");

        //adjust size and set layout
        setPreferredSize (new Dimension (650, 470));
        setLayout (null);

        //add components
        add (zehnc);
        add (zwanzigc);
        add (eins);
        add (fuenfc);
        add (fuenfzig);
        add (jcomp6);
        add (jcomp7);
        add (jcomp8);
        add (jcomp9);
        add (fuenf);
        add (zehn);
        add (zwei);
        add (zwanzig);

        //set component bounds (only needed by Absolute Positioning)
        zehnc.setBounds (385, 100, 60, 45);
        zwanzigc.setBounds (455, 100, 60, 45);
        eins.setBounds (385, 150, 60, 45);
        fuenfc.setBounds (315, 100, 60, 45);
        fuenfzig.setBounds (315, 150, 60, 45);
        jcomp6.setBounds (150, 140, 100, 25);
        jcomp7.setBounds (150, 105, 100, 25);
        jcomp8.setBounds (50, 100, 100, 25);
        jcomp9.setBounds (50, 140, 100, 25);
        fuenf.setBounds (315, 200, 60, 45);
        zehn.setBounds (385, 200, 60, 45);
        zwei.setBounds (455, 150, 60, 45);
        zwanzig.setBounds (455, 200, 60, 45);
    }

    public static void main (String[] args) {
        JFrame frame = new JFrame ("Zahlung");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new GUI_bezahlung());
        frame.pack();
        frame.setVisible (true);
    }
}
